name: ${PROJECT}

services:
  whoami:
    image: "traefik/whoami"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`${HOST}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.middlewares.whoamists.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.whoamists.headers.stspreload=true"
      - "traefik.http.middlewares.whoamists.headers.stsseconds=31536000"
      - "traefik.http.middlewares.whoamissts.headers.isdevelopment=false"
      - "traefik.http.routers.service.middlewares=whoamists"
      # - "traefik.http.routers.whoami.middlewares=auth"
      # - "traefik.http.middlewares.auth.basicauth.users=mh:$$apr1$$lhkpo2by$$HLxKuazUduO73EmHExZgs/"

    networks:
      - net

networks:
  net:
    name: traefik_net
    external: true
