version: "3.9"

networks:
  net:
    external:
      name: traefik_net

services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.qxf.de`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.middlewares.whoami.basicauth.users=mh:$$apr1$$lhkpo2by$$HLxKuazUduO73EmHExZgs//"

    networks:
      - net
